include "application"

http.port = 9664
mongo.uri = "mongodb://"${MONGO_USER}":"${MONGO_PASSWORD}"@mongo:27017/lichess?authSource=admin"
study.mongo.uri = ${mongo.uri}
redis.uri = "redis://:"${REDIS_PASSWORD}"@redis:6379"
csrf.origin = ${LITAK_ORIGIN}
netty.useEpoll = false
