include "application"

mongodb.uri = "mongodb://"${MONGO_USER}":"${MONGO_PASSWORD}"@mongo:27017/?authSource=admin"
redis.uri = "redis://:"${REDIS_PASSWORD}"@redis:6379"

net {
  domain = ${LITAK_DOMAIN}
  socket.domains = [ ${LITAK_WS_DOMAIN} ]
  asset.domain = ${net.domain}
  asset.base_url = ${LITAK_BASE_URL}
  asset.minified = true
  base_url = ${LITAK_BASE_URL}
  ip = ${LITAK_PUBLIC_IP}
  email = ${LITAK_ADMIN_EMAIL}
  crawlable = true
  stage.banner = false
}

play.http.secret.key = ${LITAK_PLAY_SECRET}
user.password.bpass.secret = ${LITAK_PASSWORD_SECRET}
